const actionTypes = {
  GET_USER_INPUT: 'GET_USER_INPUT',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',
  LIKEDISLIKE_ARTICLE: 'LIKEDISLIKE_ARTICLE',
  GET_ARTICLE: 'GET_ARTICLE',
  GET_LIKE_STATUS: 'GET_LIKE_STATUS',
  USER_LOGIN: 'USER_LOGIN',
  USER_REGISTRATION: 'USER_REGISTRATION',
};

export default actionTypes;
