const ACTION_TYPE = {
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  USER_REGISTRATION: 'USER_REGISTRATION',
  CHANGE_LOGIN_FIELDS: 'CHANGE_LOGIN_FIELDS',
  GET_USER_INPUT: 'GET_USER_INPUT',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',
  GET_RATING_SUCCESS: 'GET_RATING_SUCCESS',
  POST_RATING_SUCCESS: 'POST_RATING_SUCCESS',
  POST_RATING_DATA: 'POST_RATING_DATA',
};

export default ACTION_TYPE;
