const ACTION_TYPE = {
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  USER_REGISTRATION: 'USER_REGISTRATION',
  CHANGE_LOGIN_FIELDS: 'CHANGE_LOGIN_FIELDS',
  GET_USER_INPUT: 'GET_USER_INPUT',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',
  USER_LOGIN: 'USER_LOGIN',
  SOCIAL_LOGIN: 'SOCIAL_LOGIN_SUCCESS',
  LOGIN: 'LOGIN',
  TEST: 'TEST',
  SOCIAL_LOGIN_FAILURE: 'SOCIAL_LOGIN_FAILURE',

};
export default ACTION_TYPE;
